// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pb/resizer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resizer_Resize_FullMethodName = "/pb.Resizer/Resize"
)

// ResizerClient is the client API for Resizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResizerClient interface {
	Resize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResizeRequest, ResizeResponse], error)
}

type resizerClient struct {
	cc grpc.ClientConnInterface
}

func NewResizerClient(cc grpc.ClientConnInterface) ResizerClient {
	return &resizerClient{cc}
}

func (c *resizerClient) Resize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResizeRequest, ResizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Resizer_ServiceDesc.Streams[0], Resizer_Resize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResizeRequest, ResizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Resizer_ResizeClient = grpc.BidiStreamingClient[ResizeRequest, ResizeResponse]

// ResizerServer is the server API for Resizer service.
// All implementations must embed UnimplementedResizerServer
// for forward compatibility.
type ResizerServer interface {
	Resize(grpc.BidiStreamingServer[ResizeRequest, ResizeResponse]) error
	mustEmbedUnimplementedResizerServer()
}

// UnimplementedResizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResizerServer struct{}

func (UnimplementedResizerServer) Resize(grpc.BidiStreamingServer[ResizeRequest, ResizeResponse]) error {
	return status.Error(codes.Unimplemented, "method Resize not implemented")
}
func (UnimplementedResizerServer) mustEmbedUnimplementedResizerServer() {}
func (UnimplementedResizerServer) testEmbeddedByValue()                 {}

// UnsafeResizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResizerServer will
// result in compilation errors.
type UnsafeResizerServer interface {
	mustEmbedUnimplementedResizerServer()
}

func RegisterResizerServer(s grpc.ServiceRegistrar, srv ResizerServer) {
	// If the following call panics, it indicates UnimplementedResizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resizer_ServiceDesc, srv)
}

func _Resizer_Resize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResizerServer).Resize(&grpc.GenericServerStream[ResizeRequest, ResizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Resizer_ResizeServer = grpc.BidiStreamingServer[ResizeRequest, ResizeResponse]

// Resizer_ServiceDesc is the grpc.ServiceDesc for Resizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Resizer",
	HandlerType: (*ResizerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Resize",
			Handler:       _Resizer_Resize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/resizer.proto",
}
