// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pb/resizer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ResizeRequest_Metadata
	//	*ResizeRequest_Chunk
	Payload       isResizeRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_pb_resizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_resizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_pb_resizer_proto_rawDescGZIP(), []int{0}
}

func (x *ResizeRequest) GetPayload() isResizeRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResizeRequest) GetMetadata() *ResizeMetadata {
	if x != nil {
		if x, ok := x.Payload.(*ResizeRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ResizeRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ResizeRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isResizeRequest_Payload interface {
	isResizeRequest_Payload()
}

type ResizeRequest_Metadata struct {
	Metadata *ResizeMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ResizeRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ResizeRequest_Metadata) isResizeRequest_Payload() {}

func (*ResizeRequest_Chunk) isResizeRequest_Payload() {}

type ResizeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	ArchiveType   string                 `protobuf:"bytes,2,opt,name=archive_type,json=archiveType,proto3" json:"archive_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeMetadata) Reset() {
	*x = ResizeMetadata{}
	mi := &file_pb_resizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeMetadata) ProtoMessage() {}

func (x *ResizeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_resizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeMetadata.ProtoReflect.Descriptor instead.
func (*ResizeMetadata) Descriptor() ([]byte, []int) {
	return file_pb_resizer_proto_rawDescGZIP(), []int{1}
}

func (x *ResizeMetadata) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ResizeMetadata) GetArchiveType() string {
	if x != nil {
		return x.ArchiveType
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Formats       []string               `protobuf:"bytes,4,rep,name=formats,proto3" json:"formats,omitempty"`
	Quality       int32                  `protobuf:"varint,5,opt,name=quality,proto3" json:"quality,omitempty"`
	Lossless      bool                   `protobuf:"varint,6,opt,name=lossless,proto3" json:"lossless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pb_resizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pb_resizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pb_resizer_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Task) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Task) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Task) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *Task) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Task) GetLossless() bool {
	if x != nil {
		return x.Lossless
	}
	return false
}

type ResizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ResizeResponse_Metadata
	//	*ResizeResponse_Chunk
	Payload       isResizeResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_pb_resizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_resizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_pb_resizer_proto_rawDescGZIP(), []int{3}
}

func (x *ResizeResponse) GetPayload() isResizeResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResizeResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		if x, ok := x.Payload.(*ResizeResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ResizeResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ResizeResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isResizeResponse_Payload interface {
	isResizeResponse_Payload()
}

type ResizeResponse_Metadata struct {
	Metadata *ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ResizeResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ResizeResponse_Metadata) isResizeResponse_Payload() {}

func (*ResizeResponse_Chunk) isResizeResponse_Payload() {}

type ResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_pb_resizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_resizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_pb_resizer_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ResponseMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_pb_resizer_proto protoreflect.FileDescriptor

const file_pb_resizer_proto_rawDesc = "" +
	"\n" +
	"\x10pb/resizer.proto\x12\x02pb\"d\n" +
	"\rResizeRequest\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.pb.ResizeMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"S\n" +
	"\x0eResizeMetadata\x12\x1e\n" +
	"\x05tasks\x18\x01 \x03(\v2\b.pb.TaskR\x05tasks\x12!\n" +
	"\farchive_type\x18\x02 \x01(\tR\varchiveType\"\x96\x01\n" +
	"\x04Task\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x18\n" +
	"\aformats\x18\x04 \x03(\tR\aformats\x12\x18\n" +
	"\aquality\x18\x05 \x01(\x05R\aquality\x12\x1a\n" +
	"\blossless\x18\x06 \x01(\bR\blossless\"g\n" +
	"\x0eResizeResponse\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.pb.ResponseMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"Q\n" +
	"\x10ResponseMetadata\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2>\n" +
	"\aResizer\x123\n" +
	"\x06Resize\x12\x11.pb.ResizeRequest\x1a\x12.pb.ResizeResponse(\x010\x01B\x12Z\x10image-resizer/pbb\x06proto3"

var (
	file_pb_resizer_proto_rawDescOnce sync.Once
	file_pb_resizer_proto_rawDescData []byte
)

func file_pb_resizer_proto_rawDescGZIP() []byte {
	file_pb_resizer_proto_rawDescOnce.Do(func() {
		file_pb_resizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_resizer_proto_rawDesc), len(file_pb_resizer_proto_rawDesc)))
	})
	return file_pb_resizer_proto_rawDescData
}

var file_pb_resizer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_resizer_proto_goTypes = []any{
	(*ResizeRequest)(nil),    // 0: pb.ResizeRequest
	(*ResizeMetadata)(nil),   // 1: pb.ResizeMetadata
	(*Task)(nil),             // 2: pb.Task
	(*ResizeResponse)(nil),   // 3: pb.ResizeResponse
	(*ResponseMetadata)(nil), // 4: pb.ResponseMetadata
}
var file_pb_resizer_proto_depIdxs = []int32{
	1, // 0: pb.ResizeRequest.metadata:type_name -> pb.ResizeMetadata
	2, // 1: pb.ResizeMetadata.tasks:type_name -> pb.Task
	4, // 2: pb.ResizeResponse.metadata:type_name -> pb.ResponseMetadata
	0, // 3: pb.Resizer.Resize:input_type -> pb.ResizeRequest
	3, // 4: pb.Resizer.Resize:output_type -> pb.ResizeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_resizer_proto_init() }
func file_pb_resizer_proto_init() {
	if File_pb_resizer_proto != nil {
		return
	}
	file_pb_resizer_proto_msgTypes[0].OneofWrappers = []any{
		(*ResizeRequest_Metadata)(nil),
		(*ResizeRequest_Chunk)(nil),
	}
	file_pb_resizer_proto_msgTypes[3].OneofWrappers = []any{
		(*ResizeResponse_Metadata)(nil),
		(*ResizeResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_resizer_proto_rawDesc), len(file_pb_resizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_resizer_proto_goTypes,
		DependencyIndexes: file_pb_resizer_proto_depIdxs,
		MessageInfos:      file_pb_resizer_proto_msgTypes,
	}.Build()
	File_pb_resizer_proto = out.File
	file_pb_resizer_proto_goTypes = nil
	file_pb_resizer_proto_depIdxs = nil
}
